theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Wiki Fluff Radio
description: Documentation et guides de configuration OBS pour les streamers
lang: fr
default_lang: fr
languages:
  - fr
  - en
permalink: pretty
show_downloads: false
